save_dir: ./saved_models
save_name: remixmatch_RAF_DB_175_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 175
batch_size: 64
eval_batch_size: 1024
alpha: 0.75
T: 0.5
ulb_loss_ratio: 1.0
w_kl: 0.5
w_match: 1.5
w_rot: 0.5
use_dm: True
use_xe: True
warm_up: 0.015625
uratio: 1
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: ResNet18
net_from_name: False
depth: 0
widen_factor: 0
leaky_slope: 0.1
dropout: 0.0
data_dir: /scratch/a/amiilab/shuvendu/data/RAF-DB
train_sampler: RandomSampler
num_classes: 7
num_workers: 1
alg: remixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10206
dist_backend: nccl
gpu: None
