save_dir: ./saved_models
save_name: mixmatch_affectnet_70_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 70
batch_size: 64
eval_batch_size: 1024
uratio: 1
alpha: 0.5
T: 0.5
ulb_loss_ratio: 100
ramp_up: 0.4
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: ResNet18
net_from_name: False
depth: 0
widen_factor: 0
leaky_slope: 0.1
dropout: 0.0
data_dir: /scratch/a/amiilab/shuvendu/data/AffectNet
train_sampler: RandomSampler
num_classes: 7
num_workers: 1
alg: mixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10308
dist_backend: nccl
gpu: None
